### ISSUE TITLE
There is not src/booleanField.js and Scalar function in npm package of algebra@0.8.0

### ISSUE THREAD

**Issue by xgbuils** [fibo/algebra#4]
Hi @fibo 

I see your PR in awesome-nodejs and I find this package interesting. I'm trying to use the file 'src/booleanField.js' mentioned in README.md to do some tests but there is not in the last version (0.8.0) of npm package. It is not a blocker for me but I want to report it in case that you were not noticed about it.

Regards!

**Comment by xgbuils** [comment]
Sorry, I've seen that in npm documentation is not mentioned 'src/booleanField.js'. All is well synchronized.

**Comment by fibo** [comment]
Hi @xgbuils , thanks for your interest.

Please note that the boolean field definition should work as expected (see [test/booleanField.js](https://github.com/fibo/algebra/blob/master/test/booleanField.js)) but the Byte example reported in README is not working yet.

While I am already using Complex, Quaternion and so on as composition algebras over Real, the *Byte as Octonion over Booleans* example still does not work due to a minor issue I could not solve.

I am looking forward to see what happen to bytes if they are in a Fano plane :)
